FROM python:3.8-slim

# Set working directory
WORKDIR /app

# Install necessary packages and upgrade pip
RUN apt-get update && \
    apt-get install -y postgresql-client curl && \
    pip install --upgrade pip

# Copy and install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the entire application code
COPY . .

# Set Python path
ENV PYTHONPATH=/app

# Install testing frameworks
RUN pip install pytest pytest-flask

# Define the default command to run tests
CMD ["pytest"]
