# Use an official Python runtime as a parent image
FROM python:3.8-slim

# Set the working directory
WORKDIR /app

# Install necessary packages
RUN apt-get update && \
    apt-get install -y postgresql-client curl && \
    pip install --upgrade pip

# Copy requirements.txt and install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the current directory contents into the container at /app
COPY . .

# Set the PYTHONPATH environment variable
ENV PYTHONPATH=/app

# Install test dependencies
RUN pip install pytest pytest-flask

# Command to run tests
CMD ["pytest"]
